spring.application.name=app
server.port=${PORT:8080}
#Configure RSA key pair
rsa.private-key=${RSA_PRIVATE_KEY_PATH:classpath:certs/private.pem}
rsa.public-key=${RSA_PUBLIC_KEY_PATH:classpath:certs/public.pem}
#Database Connection Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hh3d?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Configuring Spring Data JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect